### PR TITLE
Add code-coverage and test-cases to workflow

### LINKED ISSUE #23: Automate regression testing
Automated regression testing would let us make changes with the confidence that functionality and performance regressions are caught fast. 

To avoid changing DOSBox's internal code (with whitebox tests), a blackbox approach would allow non-developers to contribute cases. 

A test case would involve feeding DOSBox a custom dosbox.conf file (setting particular features), running a DOS program that generates some capturable result (then quits on its own when done), and finally comparing the captured result to a previously saved known-good result.

The test harness could also record metadata such as test runtime, memory usage, latency, etc - so performance and resource uses could at least be measured and more importantly trended or flagged. (although some tolerance would be included as we aren't guaranteed isolated and identical CI VM hardware). 

Getting this off the ground would involve modifying DOSBox so it can run headless; currently it fails to even start if SDL can't latch onto an active display.  We would need to find or write representative DOS programs that exercise some singular element of common game functionality: real mode, protected mode, EGA, VGA, SoundBlaster, GUS, and so on. For now, simply having DOSBox run "hello world" would let us get the framework in place.

### PR DESCRIPTION
**Pull request by krcroft**
This PR adds:
- code-coverage support to our build and package scripts
- a specification for adding test-cases to the `contrib` area
- scripts that setup and run the tests-cases (either headless or locally)

These three come together in our analysis workflow, which now has a coverage job.
The job builds an instrumented binary, runs the test-cases, and then generates an HTML report plus pushes the coverage data to https://codecov.io/gh/dreamer/dosbox-staging

You can run tests locally with:
1. `./contrib/scripts/setup-tests.sh` (first-time only)
2. `./contrib/scripts/run-tests.sh`

Effort is made to run each step in parallel to save time because result-determination is automatic and doesn't require inspect or witnessing the run.

A single failure in any test will cause the entire test run to fail (and fail the workflow).

Fixes #23

### CODE REVIEW

**Comment by krcroft** [comment]
Some screenshots from the workflow and HTML report (downloadable asset)

**Comment by krcroft** [comment]
Because this lets us test actual game functionality in both the positive and deliberate-fail cases in DOSbox, I think this fixes #23.

Next tests I want to add are sunny-day-scenario cd-da mounts and unmounts for pure bin-images, wav, flac, mp3, opus, and vorbis (and run playback), along with deliberate failure handling for invalid cues, broken iso and bin, and corrupt audio files. (this will be the basis for adding cue-mounted directories).

**Comment by dreamer** [comment]
I haven't forgotten about this review, just couldn't look into details yet.

Overall I like the approach and technically I think it's a good solution - my gripes are more non-technical. I'll try to review this PR properly this week :)

**Comment by krcroft** [comment]
Thanks @dreamer_, definitely no rush on this. There's a fair bit here (however the scripts are thin and simple), so we can take our time to adjust the structure or scripts if it means handling other use-cases.

**Comment by dreamer** [comment]
Hmm, I like this solution a lot, but I think we'll need a slightly different approach.

1. (tiny issue, probably easy to resolve) - I don't have `gdown` installed and it's not available in my repo. Not sure where to get it from. Overall I have mixed feelings about depending on Google for too much of storage this way.
2. I imagine comprehensive testcase like this would be very beneficial for bisecting project history looking for regressions, or comparing 2 different builds of dosbox (also SVN or DOSBox-X). Placing it inside the repo in contrib does not help with that - having these testcases outside of repo would make it somewhat easier.
3. I do agree that there should be no legal issues with these, but I'm still worried that placing download links for files with murky licenses in the repo might bite us later down the line. I think Linux distributions (especially the ones that pay close attention to the licensing issues like Debian and Fedora) will have problem using our tarball releases.
4. I think developing a comprehensive test suite will be faster without a strict code review process we have in this repo.

To address all of above, I suggest the following solution: I'll create a new Git repo, on GitLab (`dosbox-staging-tests`?) and add you with the admin role. Contributions to that repo would not be gated via reviews (so more traditional cooperation on a branch, by simply pushing/pull and being generally responsible) - except outside contributions, of course.

Instead of downloading binary artifacts from gdrive, we could place them directly in repo using LFS (it is really easy to use). The reason why I prefer to go with GitLab in this case is amount of available LFS space - I think there's like 20 or 30GB available compared to somewhat limited space and monthly transfer limits on GitHub. This would also allow us to include wider range of DOS software in the repo.

The structure you developed for the tests in this PR is very good and would be a great starting point for new repo. @krcroft What do you think?

**Comment by krcroft** [comment]
@dreamer ; I agree with all your points and I like the idea of an out-of-band pool of tests for bisecting. 

It will be nice to have all the content together as a self-contained package, and avoid all this fragmentation and relying on 3rd party hosting (spent more time wrestling with how to separate and bring it back together then on the tests themselves!). This will let me make some improvements.

There's a user on vogons named root42 who hosts a "let's code DOS software" youtube series.  I would envision someone like him writing writing tiny executables that exercise 1-to-1 some feature in DOSBox - ideally with arguments so we could walk through a swath of variations in the tests (ie: SB16 210, 220, 230, 240, then IRQ3, 5, and 7, ... and so on).

Some examples: 
- https://www.youtube.com/watch?v=isgjKcvGDSk
- https://www.youtube.com/watch?v=LhMcxl7giP8

When we hit regressions, a new executable would be produced to exercise and test the correct behavior, and we'd add it to the suite. Eventually 

Regarding the PR- will take it down, and will regroup on Gitlab. Once I get it working, the next PR here might be a bisect-helper, that can generically tie into a specific test case.   Thanks for the suggestions and moving this forward.

**Comment by dreamer** [comment]
Yeah, I was looking into compiling small DOS executables for testing as well - even set up environment using Turbo Pascal (it has nice library bundled and even includes `make`, so tests are easier to compile inside DOSBox). Initially, I wanted to use FreePascal, but cross-compiler for DOS is not included in Fedora fpc package and seems annoying to set up.

I'll create a new repository, configure it for storing zstd files as LFS artifacts as example, and send you instructions and quick LFS tutorial via mail :) LFS is pretty cool and easy to use, but I remember having problems finding good "quick overview" documentation when I started using it.

**Comment by krcroft** [comment]
> I'll create a new repository, configure it for storing zstd files as LFS artifacts as example, and send you instructions and quick LFS tutorial via mail :) LFS is pretty cool and easy to use, but I remember having problems finding good "quick overview" documentation when I started using it

Roger that! Thank you @dreamer!

**Pull request closed without merging**
