### PR TITLE
Force POSIX usage for MinGW

### PR DESCRIPTION
**Pull request by dreamer**
@ant-222 please confirm this branch is buildable in your environment without any additional patches.

### CODE REVIEW

**Comment by ant-222** [comment]
> 
> 
> @ant-222 please confirm this branch is buildable in your environment without any additional patches.

No, it it is not:

~~~
In file included from ../../include/dos_system.h:26,
                 from ../../include/dos_inc.h:24,
                 from ../../include/drives.h:29,
                 from drive_local.cpp:22:
drive_local.cpp: In member function 'virtual bool localFile::Write(Bit8u*, Bit16u*)':
../../include/cross.h:70:25: error: 'fileno' was not declared in this scope
 #define cross_fileno(s) fileno(s)
                         ^~~~~~
../../include/cross.h:58:38: note: in definition of macro 'ftruncate'
 #define ftruncate(blah,blah2) chsize(blah,blah2)
                                      ^~~~
drive_local.cpp:522:21: note: in expansion of macro 'cross_fileno'
   return !ftruncate(cross_fileno(fhandle), ftell(fhandle));
                     ^~~~~~~~~~~~
../../include/cross.h:70:25: note: suggested alternative: 'Files'
 #define cross_fileno(s) fileno(s)
                         ^~~~~~
../../include/cross.h:58:38: note: in definition of macro 'ftruncate'
 #define ftruncate(blah,blah2) chsize(blah,blah2)
                                      ^~~~
drive_local.cpp:522:21: note: in expansion of macro 'cross_fileno'
   return !ftruncate(cross_fileno(fhandle), ftell(fhandle));
                     ^~~~~~~~~~~~
drive_local.cpp: In member function 'virtual bool localFile::UpdateDateTimeFromHost()':
../../include/cross.h:70:25: error: 'fileno' was not declared in this scope
 #define cross_fileno(s) fileno(s)
                         ^~~~~~
drive_local.cpp:588:8: note: in expansion of macro 'cross_fileno'
  fstat(cross_fileno(fhandle), &temp_stat);
        ^~~~~~~~~~~~
../../include/cross.h:70:25: note: suggested alternative: 'Files'
 #define cross_fileno(s) fileno(s)
                         ^~~~~~
drive_local.cpp:588:8: note: in expansion of macro 'cross_fileno'
  fstat(cross_fileno(fhandle), &temp_stat);
        ^~~~~~~~~~~~
make[3]: *** [drive_local.o] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
~~~

**Comment by ant-222** [comment]
Being a Windows development environment, *MinGW* does not claim to support *POSIX*. I think we have to use Microsoft's [`_fileno`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fileno?view=vs-2019), which *MinGW* provides as a macro. `cross.h` can take care of it.

**Comment by dreamer** [comment]
I tested it on my MinGW setup and it definitely worked in there (for everything except `%zu`). I am tired of forcing GCC on some old MinGW to behave like a sane compiler would (when Clang does not need such tiptoeing around and even modern MSVC works ok). In next revision I will simply set GNU extensions to be used; I someone will try to abuse it, we will detect it by compilation on Clang or MSVC and block during review.

**Comment by krcroft** [comment]
(only stating this for historic reasons) but  this is confirmed working for MinGW 32 and 64bit gcc 9.2x (circa Feb-2020) when installed by MSYS2.

**Comment by krcroft** [comment]
> In the next revision I will enableGNU extensions; if someone abuses it, we will detect it by compilation on Clang or MSVC

Sounds like a well-measured compromise! 👍

**Comment by dreamer** [comment]
I included the missing include; @ant-222 please confirm the branch builds now on your machine without any additional changes.

**Comment by ant-222** [comment]
> (only stating this for historic reasons) but this is confirmed working for MinGW 32 and 64bit gcc 9.2x (circa Feb-2020) when installed by MSYS2.

The *MinGW* distribution includes *MSYS1* and does not support *MSYS2*. Maybe *MSYS2* installs a lateral branch of *MingW* called *Mingw-w64*? That is not what I use.

**Comment by krcroft** [comment]
Thanks for the clarification @ant-222; I've updated the original comment.

**Comment by dreamer** [comment]
@ant-222 
- MinGW treating `fileno` differently than `ftruncate` is a bug. Both these functions are defined in POSIX, and not ISO. They should either both be available or both missing, but you see compilation problems only for `fileno`.
- MinGW treating C99 code differently (but only on Windows XP) when it is being compiled using C++11 is a bug. It simply should not happen and I don't care about MinGW maintainers opinions about pedantic ansi behaviour - no other compilers cause us grief here, only GCC on MinGW.
- Not handling _POSIX_C_SOURCE correctly (as it was defined in the first version of this review) - it **should** work. Same for _XOPEN_SOURCE. But when investigating why it might not work, I found that older versions of glibc had bugs in interpreting this macro. Supposedly fixed in glibc 2.12, but maybe only on Linux.
- MinGW inability to handle printf flags correctly (`%zu` and `PRI*`) - again only in GCC in MinGW - it works on some Windows installations but does not work on others. It is widely-reported issue and the usual workaround is to define _POSIX_C_SOURCE… except it does not work for us (it was a reproducible issue on our CI in MSYS2). After setting GNU extensions - ["magically" it now works](https://github.com/dreamer/dosbox-staging/runs/477962598).

For all the problems I listed above, we were testing on different Windows versions (XP, 10, Server 2019), different MSYS versions (MSYS1, MSYS2), compilation for different architectures, different compiler versions, etc, etc. The only unifying part is usage of MinGW, therefore I conclude that's where the root causes lie. I don't care enough about MinGW to investigate them all in detail and report to MinGW maintainers *especially since I could not reproduce any of above issues in my MSYS2 on Windows 10 installation*.

Hopefully, it explains why I want to document MinGW as being the buggy part :)

Development environment on Apple is still [the worst](https://github.com/dreamer/dosbox-staging/issues/148#issuecomment-581607035) in the number of stupid problems it's causing, but MinGW is very close second ;)

Waiting for the review approval.

**Comment by ant-222** [comment]
> MinGW treating `fileno` differently than `ftruncate` is a bug. Both these functions are defined in POSIX, and not ISO. They should either both be available or both missing, but you see compilation problems only for `fileno`.

No. `ftruncate()` is available because `cross.h` defines it manually:
~~~
#if defined (WIN32)
#define ftruncate(blah,blah2) chsize(blah,blah2)
#endif
~~~

If *MinGW* provides any *POSIX* functionality, it is a courtesy.

> MinGW treating C99 code differently (but only on Windows XP) when it is being compiled using C++11 is a bug.

Differently from what? I don't understand what behavior you are referring to. On other operating systems than *Windows XP*, did you test the real [*MinGW*](http://mingw.org/) or its branch [mingw-w64](https://mingw-w64.org/doku.php)?

> It simply should not happen and I don't care about MinGW maintainers opinions about pedantic ansi behaviour - no other compilers cause us grief here, only GCC on MinGW.

Consider it a collusion of all the other compilers... In order to call some behavior a bug, one must show what official requirement, specification, or standard a product violates, not what other compiler writers have decided to do.

> Not handling _POSIX_C_SOURCE correctly (as it was defined in the first version of this review) - it **should** work.

Why should *MinGW* handle it correctly if it does not pretend to support *POSIX*?

> Same for _XOPEN_SOURCE. But when investigating why it might not work, I found that older versions of glibc had bugs in interpreting this macro. Supposedly fixed in glibc 2.12, but maybe only on Linux.

It is not [obliged to](https://sourceforge.net/p/mingw/mailman/message/35799582/):

> I would also emphasize that, in the case of MinGW, an appropriate 
definition of _XOPEN_SOURCE will never achieve _full_ conformance to 
any version of the X/Open standard, since only a small subset of it 
is actually supported; if you expect otherwise, you will surely be 
sadly disappointed.

It is not a bug, but the intended behavior.

> MinGW inability to handle printf flags correctly (`%zu` and `PRI*`) - again only in GCC in MinGW - it works on some Windows installations but does not work on others. It is widely-reported issue and the usual workaround is to define _POSIX_C_SOURCE… except it does not work for us (it was a reproducible issue on our CI in MSYS2). After setting GNU extensions - ["magically" it now works](https://github.com/dreamer/dosbox-staging/runs/477962598).

I have failed to reproduce the problem. The following program compiles with `-std=c++11` and works:
~~~
#include <stdio.h>
#define __STDC_FORMAT_MACROS // because glibc conforms to C99
#include <inttypes.h>
int main( void )
{  size_t  sz;
   int32_t i32;
   sz  = 55;
   i32 = 13;
   printf("sz: %zu; i32: %" PRIi32 ".\n", sz, i32);
   return 0;
}
~~~
> 
> 
> For all the problems I listed above, we were testing on different Windows versions (XP, 10, Server 2019), different MSYS versions (MSYS1, MSYS2), compilation for different architectures, different compiler versions, etc, etc. The only unifying part is usage of MinGW, therefore I conclude that's where the root causes lie.

> I don't care enough about MinGW to investigate them all in detail and report to MinGW maintainers _especially since I could not reproduce any of above issues in my MSYS2 on Windows 10 installation_.

I am using the original [*MinGW*](http://mingw.org/), whereas I fear that you are using its branch called [*MinGW*](http://mingw.org/). We are not testing the same thing?

**Comment by krcroft** [comment]
@ant-222 , so we just need `__STDC_FORMAT_MACROS`?

**Comment by ant-222** [comment]
> @ant-222 , so we just need `__STDC_FORMAT_MACROS`?

That is what I had to do to make it work in my *MinGW*. It will not harm the compilation on other platforms. The question explained [here](https://en.cppreference.com/w/cpp/types/integer):

> The C99 standard suggests that *C++* implementations should not define the above limit, constant, or format macros unless the macros `__STDC_LIMIT_MACROS`, `__STDC_CONSTANT_MACROS` or `__STDC_FORMAT_MACROS` (respectively) are defined before including the relevant C header (`stdint.h` or `inttypes.h`). This recommendation was not adopted by any *C++* standard and was removed in *C11*. However, some implementations (such as glibc 2.17) try to apply this rule, and it may be necessary to define the `__STDC` macros; *C++* compilers may try to work around this by automatically defining them in some circumstances.

**Comment by dreamer** [comment]
> > MinGW treating `fileno` differently than `ftruncate` is a bug. Both these functions are defined in POSIX, and not ISO. They should either both be available or both missing, but you see compilation problems only for `fileno`.
> 
> No. `ftruncate()` is available because `cross.h` defines it manually:

Then `fstat`. Whatever.

> Differently from what? I don't understand what behavior you are referring to. On other operating systems than _Windows XP_, did you test the real [_MinGW_](http://mingw.org/) or its branch [mingw-w64](https://mingw-w64.org/doku.php)?

I don't even know what version of MinGW is distributed via MSYS2; I don't care. If MinGW is buggy by design, then it's still buggy. Even Microsoft supports these POSIX functions now in modern MSVC.

> I have failed to reproduce the problem. The following program compiles with `-std=c++11` and works:

And I have failed to reproduce the problem visible only in your environment. For me, `fileno` "just works".

> I am using the original [_MinGW_](http://mingw.org/), whereas I fear that you are using its branch called [mingw-w64](https://mingw-w64.org/doku.php)? We are not testing the same thing?

I don't care about different MinGW distributions. I don't even use the damn thing for day-to-day development - I am Linux developer. The amount of time I spent caring about Windows-specific build system issues is seriously too much.

> > @ant-222 , so we just need `__STDC_FORMAT_MACROS`?

We tried it - it didn't work (or rather: worked on Windows 10, didn't work when compiling on Windows Server 2019). Enabling GNU extensions is the first thing that finally correctly compiled `%zu` across the board.

Arguing about opinions of "what constitutes a bug in development environment" is really unproductive. I'm merging this in, EOT.

**Comment by krcroft** [comment]
This is really sloppy governance by the C++ committees.

We are a group of cooperating developers just trying to write and compile C++, and due to such sloppy governance we have to drill into language specs, exclusions, a gray scale of posix implementation differences. 

They should bring the hammer down hard on these frustrating edge cases, because its harming the language and users. 

They've lets mingw developers declare their own sub-sect of c++ by hiding hiding behind the sliding scale of not-fully-posix-compliant. Well, that's maybe true.. but it's harm users like us.  

They should just declare projects "not fit for use", and shame them into consistency.

I think that's why modern languages like Go, Rust, and Python spend so much effort on governance.. they want to avoid the debacle caused by c++.

**Pull request merged**
