### PR TITLE
Organize files in Solution

### PR DESCRIPTION
**Pull request by pmcmorris**
Add a filters file to organize the project files into a folder structure that matches the on disk layout. It doesn't affect the build build but is much easier to browse.

### CODE REVIEW

**Comment by dreamer** [comment]
@pmcmorris ah, I guess it will result in VS not merging all the source files in a single list any more? Thanks! :) (I will test it out next time I'll reboot to Windows)

It seems like PVS analyser refuses to work correctly again - it's not related to your changes, you can ignore it.

@kcgen it seems like PVS works correctly only when either of us triggers the CI event… Perhaps we should move it to a separate master-only workflow, the same way we dealt with Coverity?

**Comment by pmcmorris** [comment]
Exactly, it just does this kind of thing:
image

**Comment by dreamer** [comment]
It seems like these filters are defined one-per-file… I just checked and it seems like VS [does not support wildcards](https://docs.microsoft.com/en-us/cpp/build/reference/vcxproj-file-structure?view=vs-2019) :( We don't add or move the files around very often, so it's not a big issue. 

Alternatively, we could add small python script to verify if filters xml file is up-to-date (and add it to CI), but it's out of scope of this PR.

**Comment by kcgen** [comment]
Wow.. that's hilarious VS doesn't by-default provide the same logical structure as indicated by relative path for each file. 

I can imagine that, prior to this patch, working on DOSBox in VS would have been a complete mess! This patch is going to be a game-changer for the VS users; thanks @pmcmorris!

**Comment by kcgen** [comment]
Yes; looks GitHub doesn't reveal secrets for pushes by-non project members (otherwise anyone could do 'drive by secret dumps' on random projects simply by PR'ing a change that echo the secret variables to a file and the  cat'ing it to reveal them).

PVS is a strong gatekeeper pre-merge; I would hate to accept PRs and then for us jave to do follow-up PVS cleanup in master. 

One approach that should work would be to cache it's resulting license file; so subsequent CI runs (after each version bump of pvs) will have it restored with the cache, regardless of who is PR'ing (because the cache is repo-specific on user-specific). Will make a PR for this and see how it goes.

**Comment by dreamer** [comment]
@kcgen I wouldn't call it a mess - this filters feature in VS is there to accommodate codebases, with disorganized files all over the place (and in dosbox it's pretty clean, so it makes sense to duplicate the file structure).

With this PR merged + new clang-formatting rules (VS can handle clang-format nowadays, the same way as vim or emacs) + few additional documentation changes - Windows developers working in VS will feel right at home :)

I still need to test it in second VS installation to double-check if IDE won't inject any user-specific identifiers or paths on start or won't start generating some non-ignored files. I will do it as soon as I'll have access to my Win10 machine.

**Comment by kcgen** [comment]
> this filters feature in VS is there to accommodate codebases, with disorganized files all over the place

**Comment by dreamer** [comment]
I rebase the commit, slightly touched the commit message, it's now merged as 48c7add817eb4681c6d47a8353df61f959c77eb0.

@pmcmorris Thanks! :)

**Pull request closed without merging**
