### PR TITLE
Add a commit-check to our periodic workflows

### PR DESCRIPTION
**Pull request by krcroft**
(some context) In terms of gating pushes and PRs, we have two types of workflow jobs - those that can block and those that can't. Examples of blockers are the linters and the warning counters; where as the dynamic sanitizers, Coverity scan, and the config-heavy job don't have hard checks in them.

So the first thing this PR does is move those "not blockers" to once-a-day crons; we shouldn't have to wait for them on every push.

The downside with daily crons is that they execute no matter what, even if the repo is the same as the prior day; which is wasteful and eats VM slots that we might be using. 

So this PR also checks that `master` had a commit during the prior 24 hours.  It's a bit verbose by needing an "if: <condition>" added to each step, but I don't think GitHub offers any more elegant method.

A third small change is to caps the config-heavy run to 8 processes to stay with good netiquette of only opening up to 8 parallel streams (from the Chocolatey and MSYS2 servers).

### CODE REVIEW

**Comment by krcroft** [comment]
> I grew to like dynamic sanitizers run on every push (I have an important fix lined up and used it to verify)

Oh, ok! I should revisit your warning/bug counting scripts and add them to the sanitizers and PVS output; because these checkers bring a lot more value to us if they can flag new issues for a givn push on our branches, instead of passively discovering them sometime later if/when we check the nightly reports.

I will close this PR and work on the above approach.

**Comment by krcroft** [comment]
Unfortunately this doesn't seem possible yet: https://github.com/actions/toolkit/issues/299

I've exhaustively tested and am unable to use `set-env` and `set-output` values in down-stream dependent jobs (both in the new job-level `if:` criteria as well as simply in steps).

I've also tried these as well:
-  env.VARIABLE
-  <job-name>.env.VARIABLE
-  jobs.<job-name>.env.VARIABLE
-  <job-name>.steps.<step-name>.env.VARIABLE
-  jobs.<job-name>.steps.<step-name>.env.VARIABLE

**Comment by dreamer** [comment]
Heh, lack of proper user documentation for Github Actions strikes again :/ I saw some solution with storing a token as a build artefact and starting next job conditionally based on it, but it seems even more convoluted solution for a piece of functionality, that should be built-in…

So going back to the previous solution with ifs inside specific steps? That one worked, right?

**Comment by krcroft** [comment]
Fascinating kludge! Crazy to see users getting ahead of the backend team on stuff like this when they have all the access and control at their disposal (and can throw resulting vars in a nosql DB Azure, keyed with the workflow hash, fed into dependent VMs). 

Yes, the prior worked.  Will refresh it for us to review.

**Pull request closed without merging**
