### PR TITLE
Remove code ifdefed for OS/2

### PR DESCRIPTION
**Pull request by dreamer**
Cleanup before replacing SDL1.2 with SDL2.

OS/2 support was introduced in DOSBox in March 2006.  OS/2 reached EOL
in December 2006.  As of 2019, this code does not serve any purpose
it only adds complexity.

DOSBox 0.74-3 was not even released for OS/2 and no-one noticed.

### CODE REVIEW

**Comment by dreamer** [comment]
I am postponing merge-in of this change for another week, as I saw **llm**  express a concern in Vogons thread and want to give a chance for Vogons users to take part in this review.

If no activity will take place for a week, then I'll just merge-it in.

**Comment by dreamer** [comment]
I'm glad you brought this up… I am a bit conflicted about files NEWS and ChangeLog files - they are fine and useful… but even in SVN, information about 0.74-3 is missing. One could argue, that 0.74-3 was released from a branch and not trunk… but so was 0.74-2 - and it is included.

Decided to do nothing for now, but maybe we should report it as an issue in SourceForge project and let upstream sort it out?

**Comment by krcroft** [comment]
I think that's a great idea to coordinate with upstream to see if there a cooperative / cohessive way of logging significant changes; because having these changelogs go stale is no help to anyone.

**Comment by dreamer** [comment]
**DosFreak** pointed out, that ArcaOS is continuation of OS/2. https://www.vogons.org/viewtopic.php?p=804898#p804898

ArcaOS is costly, closed-source, proprietary, 32-bit only OS. There is no way of testing our present and future changes neither on CI nor offline.

We can't assure, that DOSBox works on that system, so let's not pretend that we support it.

**Comment by krcroft** [comment]
I agree: it's important to be clear about our boundaries, and realistic with what's feasible given the direction is to support a bug free experience on modern, supported, systems(*). 

* Supported systems being "the big three" - OS X, Windows, and Linux; if others happen to work (like actively maintained BSDs), then great. But right now we don't have the resources to wider than those, nor further back in time (like Mandrake OS 5.3, or Windows 98, and so on..).

**Comment by dreamer** [comment]
I would love to eventually list Android as 4th officially supported OS… CI has all the tools needed to compile and verify it. But SDL2 is a prerequisite for that.

**Comment by dreamer** [comment]
SDL2.0 lists **IBM OS/2 and eComStation and ArcaOS** as [not supported or abandoned](https://wiki.libsdl.org/Installation#IBM_OS.2F2_and_eComStation_and_ArcaOS) with a pledge asking for people to contribute. If ArcaOS community will make SDL2.0 officially working again, I would be ok with bringing back OS/2 support.

**Comment by dreamer** [comment]
GitHub says I "dismissed" a review (?) I clicked nothing… weird.

(for the context: review thread was about OS/2 mentions in NEW/ChangeLog and I agree with those points)

**Comment by krcroft** [comment]
Yeah, this review interface is generally good but has some quirky corner-cases. 

I just had to reapprove one of the `configure.ac`-related commits; somehow my approval was still active for the other looks commits in the PR.

**Comment by dreamer** [comment]
OK, a week has passed - it's time to merge this in. This code is blocking SDL2 implementation and there'll be no magic solution. We have one user (**josch**) on Vogons forum, who has access to ArcaOS. [When he'll have spare cycles](https://www.vogons.org/viewtopic.php?p=806103#p806103) he'll try to test compile SDL2 for ArcaOS - if it'll work, then hopefully he will be able to pinpoint parts of this patch that are relevant for DOSBox+SDL2+ArcaOS.

After this code will be merged, I'll create a branch `legacy/os2` pointing to the last commit with OS/2 still in. Anyone still caring for OS/2 is free to send PRs targetting that branch - I will be extra lenient in reviews for that branch to accommodate faster development.

If work with updating SDL2 port for ArcaOS will succeed in the future, then I'll be happy to make it enabled officially again in dosbox-staging (this time under name ArcaOS and no longer OS/2).

As for mentions in NEWS and ChangeLog: https://sourceforge.net/p/dosbox/bugs/522/
I tried to move those files to `docs/upstream` to avoid user confusion, but autoconf refuses to build when these files are missing :\

**Comment by krcroft** [comment]
I was thinking about a cdrom-free version of DOSBox, and how at that point we would live entirely behind SDL2 (video, sound, and input all via SDL2), so our OS-specific hooks would disappear? (is that true?).  That would make DOSBox as portable as SDL2, and would also make it much easier to move our code to a new build tool. 

The UK does allow software and game backups (since 1988, section 50A of their copyright act); but it often gets confused and lumped in with movies and music, which are illegal to backup for personal use.

http://www.legislation.gov.uk/ukpga/1988/48/section/50 (also attached)

page 49 in the pdf:

Computer Programs

50A Back up copies.
(1) It is not an infringement of copyright for a lawful user of a copy of a computer program to make any back up copy of it which it is necessary for him to have for the purposes of his lawful use.

(2) For the purposes of this section and sections 50B [F164, 50BA] and 50C a person is a lawful user of a computer program if (whether under a licence to do any acts restricted by the copyright in the program or otherwise), he has a right to use the program.

(3) Where an act is permitted under this section, it is irrelevant whether or not there exists any term or condition in an agreement which purports to prohibit or restrict the act (such terms being, by virtue of section 296A, void).60lh

---

If there are still countries that are in doubt, we can look at how many times software companies have pressed charges against a paying customer for making a personal backup copy (I don't think there's been a single case).  Plus, the vast majority of DOS games companies were American, French, European, or Canadian, all of which allow software backups.  So even if country X prohibits backing up software, almost all DOS game companies wouldn't have jurisdiction to press charges anyway.

With the legal side taken care of, technically the cdrom image code now produces identical MSFs as the physical CDs (even with compressed audio tracks), so there's no downside anymore.

**Comment by dreamer** [comment]
That comment is more for SDL2 thread/issue, but it still applies as this commit removes moderately-sized chunk of non-portable code (including one CD-ROM interface implementation).

As for OS/2 - [patch series 4](https://github.com/dreamer/dosbox-staging/tree/po/svn-patch-series-4) is now sent upstream and it still supports OS/2, so this review should not affect the adoption of those patches.

Merging this in.

**Comment by dreamer** [comment]
For future developers, who might want to bring back support in the form of ArcaOS port: the last version of code, that still supports OS/2 is stored on branch [**legacy/os2**](https://github.com/dreamer/dosbox-staging/tree/legacy/os2).

You can also look up what implementation exactly got removed in commit 5f9ac5eeab62e58063c2a760f6d5fdd2513b476f.

**Pull request merged**
