### PR TITLE
Add a missing include of stdio.h for snprintf().

### PR DESCRIPTION
**Pull request by ant-222**

### CODE REVIEW

**Comment by krcroft** [comment]
We actually get the missing macro error in modern-Windows as well:
https://github.com/dreamer/dosbox-staging/runs/396911342#step:9:31

>  configure.ac:29: warning: macro 'AM_PATH_SDL' not found in library
>  configure.ac:215: warning: macro 'AM_PATH_ALSA' not found in library

So this PR should fix that as well.

**Comment by dreamer** [comment]
@ant-222 
You have two commits in your branch, so simple `git commit --amend` won't be enough to fix messages in both. You have two options: fix it manually or using interactive rebase. Since you're git newbie, I suggest doing it manually first.

## Manually

To visualise what's happening, run `gitk` in the background and press F5 after every command.

You can use this sequence of commands:

1. `git reset --hard HEAD~1` - this will make your local branch point to the previous commit (one commit before HEAD of the branch)
2. `git commit --amend` - fix message of commit pointed by HEAD
3. `git cherry-pick 6e1480` - re-apply the second commit from review
4. `git commit --amend` - fix message of the second commit
5. `git push --force origin as/test-1` - force push your changes (you need to force push, because your local branch and remote branch diverged); push will automatically update the review

After step 5, open review page and re-request review, so the reviewer is notified you don't plan further changes.

## Interactive rebase

In practice repeating such steps would be tedious when you want to fix e.g. last ten commits. You could use this command to modify last two commits on the branch:

    git rebase --interactive HEAD~2

Then edit lines to be executed (read instructions show by rebase), save and exit.

**Comment by dreamer** [comment]
Oh, and one tiny thing @ant-222, @krcroft - I suggest to reconsider and use real names and emails for commit messages…

*I am not going to enforce it*, but it's nicer when a reader can see, that code author is not afraid to sign the commits. Notice, that GitHub **does not** show any mails publically **ever**, so it's impossible to scrape them - they are visible only after cloning the repo.

After changing the name/email using `git config (…)`, commit authorship can be updated using `git commit --amend --reset-author`.

**Comment by ant-222** [comment]
Patryk:

> Oh, and one tiny thing @ant-222, @krcroft—I suggest to reconsider
> and use real names and emails for commit messages...

I have no problem about using my real name, but is it safe to publish
the an unmuged e-mail too?

> Notice, that GitHub **does not** show any mails publically **ever**,
> so it's impossible to scrape them—they are visible only after
> cloning the repo.

But SPAM-bots can clone too, can they not?

> After changing the name/email using `git config (...)`, commit
> authorship can be updated using `git commit --amend --reset-author`.

Is the public profile name (*Anton Shepelev*) or the username/login
(`ant-222`) that `git config` needs?

**Comment by ant-222** [comment]
`krcroft`:

> Glad these fix issues on XP, and confirmed good on all the workflow
> platforms as well.

That cannot be specific either to *Windows XP* or to *MinGW*, for a
function shall be declared in order to be used.
The compilers in your other test systems seem to be unnecessarily
forgiving.

**Comment by ant-222** [comment]
Why is not *Markdown* recognised in my replies?
Is *Githumb* playing double standards by ignoring
*Markdown* from e-mail?

**Comment by dreamer** [comment]
> I have no problem about using my real name, but is it safe to publish the an unmuged e-mail too?

Name might show up in GitHub interface somewhere (I'm not sure), but email address never does.

> But SPAM-bots can clone too, can they not?

They can… but it means git needs to be installed and repository cloned… for each project separately. And each project would give spammer only limited number of mails, so there's no big incentive… it is much easier and more cost-effective for a spammer to subscribe to a mailing list or scrap a page looking for '@'. Personally, I don't see this as a problem, as gmail filters out practically all spam targetted at email I use here.

> Is the public profile name (*Anton Shepelev*) or the username/login (`ant-222`) that `git config` needs?

The convention in most serious open source projects is to use full name and surname (unicode is ok), so the information e.g. in `git blame` or `git shortlog` is relevant regardless of Git host - also when repo is mirrored or moved to a different host.

GitHub interface will show information based on the email address. If email address is missing from GitHub's database, then name and surname will be displayed.

**Comment by dreamer** [comment]
> `krcroft`:
> Glad these fix issues on XP, and confirmed good on all the workflow platforms as well.
> That cannot be specific either to *Windows XP* or to *MinGW*, for a function shall be declared in order to be used. The compilers in your other test systems seem to be unnecessarily forgiving.

I guess on all other systems this include is pulled in via `SDL.h` including `SDL_stdinc.h`. No idea why it doesn't work only for Windows XP builds, but I'm glad it's fixed.

**Comment by dreamer** [comment]
> Why is not *Markdown* recognised in my replies? Is *Githumb* playing double standards by ignoring *Markdown* from e-mail?

Seems like it does :\ For me it's not a problem, it's readable either way.

**Comment by ant-222** [comment]
Patryk Obara:

> I guess on all other systems this include is pulled in via
> `SDL.h` including `SDL_stdinc.h`.  No idea why it doesn't
> work only for Windows XP builds, but I'm glad it's fixed.

I can check why it does not happen at a later time, or we
can just leave the include there it forget about it.

**Comment by ant-222** [comment]
Patryk:

> 1. `git reset --hard HEAD~1` - this will make your local
>     branch point to the previous commit (one commit before HEAD of the branch)
> 2. `git commit --amend` - fix message of commit pointed by HEAD

Did it with the -m tag, because without it `git' tries to
start Vim with input and output redirected away from the
terminal.  Have an idea how to set up git to use Vim
correctly?

> 3. `git cherry-pick 6e1480` - re-apply the second commit
> from review 4. `git commit --amend` - fix message of the
> second commit

Git says:
fatal: You are in the middle of a cherry-pick -- cannot amend.

> Both commits use dots in the end of the subject
> line -- remove it please
> (https://chris.beams.io/posts/git-commit/#end).

I see.  I did not know that the commit message passed to
`git commit' via the `-m' parameter is called the subject
line.  I treated it rather as a paragraph of English prose,
consisting in general of several sentences, each ending with
a proper punctuation mark.  If it *is* a subject -- then I
agree that it shall not have a full stop at the end.

**Comment by ant-222** [comment]
Patryk:

> Name might show up in GitHub interface somewhere (I'm not
> sure), but email address never does.

So you are not receiving SPAM because of a public e-mail on
Github?  There are even scripts that extract users' e-mails:

   https://github.com/paulirish/github-email
   (Get a GitHub user's email. All sneaky-like.)

**Comment by ant-222** [comment]
I wrote to Patryk:

> > (https://chris.beams.io/posts/git-commit/#end).
>
> I see.  I did not know that the commit message passed to
> `git commit' via the `-m' parameter is called the subject
> line.

Very good article, that.  The subject, by convention, is the
first line of the commit message followed by an empty line.

> The second commit does not mention why the change is
> needed (build works fine without warnings outside of
> Windows after all). Add one-sentence with explanation to
> the commit message for future reference.

Not to the subject, but to the body, right?

**Comment by dreamer** [comment]
> Did it with the -m tag, because without it `git` tries to start Vim with input and output redirected away from the terminal. Have an idea how to set up git to use Vim correctly?

For me, msysGit/"Git for Windows" always came with correctly pre-configured vim, therefore I don't know what might be the issue.

To show what editor command is currently used:

    git config core.editor

To change it:

    git config --global core.editor <your-editor>

> Git says: fatal: You are in the middle of a cherry-pick -- cannot amend.

It means exactly what it says on the tin :) Sometime earlier you tried to do a cherry-pick, it didn't work for some reason (code conflict or some other error) and Git is confused, because it doesn't know if you're still trying to finish that cherry-pick or you moved on. To inform Git, that you don't work on that old cherry-pick any more run:

    git cherry-pick --abort

> I see. I did not know that the commit message passed to `git commit' via the `-m' parameter is called the subject line. I treated it rather as a paragraph of English prose, consisting in general of several sentences, each ending with a proper punctuation mark. If it *is* a subject -- then I agree that it shall not have a full stop at the end.

Yup, it's a title/subject :) When sending patches to a mailing lists, it is re-used as a mail subject as well. It's only a convention, but using soft-limit of 50 chars for the title has a nice effect of displaying correctly in whatever tool/frontend other users employ. And `git log --oneline` is nice and readable.

Unfortunately, commits incoming from SVN do not use this convention :(

> Not to the subject, but to the body, right?

Yes :)

BTW, if you'll have more problems with setting editor, commit message can be also specified by file:

    git commit --amend -F <message-file>

from standard input:

    git commit --amend --file=-

or message, authorship, and authorship date can be copied from some existing commit:

    git commit --amend -C <commit-id>

>> I guess on all other systems this include is pulled in via `SDL.h` including `SDL_stdinc.h`. No idea why it doesn't work only for Windows XP builds, but I'm glad it's fixed.

> I can check why it does not happen at a later time, or we can just leave the include there it forget about it.

Leave the include in, it's the cleanest solution.

**Comment by ant-222** [comment]
Patryk Obara:

> It's only a convention, but using soft-limit of 50 chars
> for the title has a nice effect of displaying correctly in
> whatever tool/frontend other users employ. And `git log
> --oneline` is nice and readable.

With the standard 80-character display, the message must be
37 characters or so, because the hash is 40 symbols.

**Comment by ant-222** [comment]
Patryk Obara to Anton Shepelev:

> For me, msysGit/"Git for Windows" always came with
> correctly pre-configured vim, therefore I don't know what
> might be the issue.

I don't know what that is.  MinGW does not provide `git'.

> To show what editor command is currently used:
>
>    git config core.editor
>
> To change it:
>
>    git config --global core.editor <your-editor>

Yes, I know that.  Will ask at the Vim mailing list,
perhaps...

> > Git says:
> > fatal: You are in the middle of a cherry-pick -- cannot amend.
>
> It means exactly what it says on the tin :) Sometime
> earlier you tried to do a cherry-pick, it didn't work for
> some reason (code conflict or some other error) and Git is
> confused, because it doesn't know if you're still trying
> to finish that cherry-pick or you moved on. To inform Git,
> that you don't work on that old cherry-pick any more run:
>
>    git cherry-pick --abort

Thank you.  How can I see my branch in a fresh clone?
`git banch' lists only `master'.

> Unfortunately, commits incoming from SVN do not use this
> convention :(

I like this idea and will try to implemented it at work.

> BTW, if you'll have more problems with setting editor,
> commit message can be also specified by file:

I have already found that out, thanks.  Will be doing that
until I set up Vim correctly.

-- 
()  ascii ribbon campaign -- against html e-mail
/\  http://preview.tinyurl.com/qcy6mjc [archived]

**Comment by ant-222** [comment]
Patryk Obara:

> 1. `git reset --hard HEAD~1` - this will make your local branch point to the previous commit (one commit before HEAD of the branch)
> 2. `git commit --amend` - fix message of commit pointed by HEAD
> 3. `git cherry-pick 6e1480` - re-apply the second commit from review

I did it again on brand new clone and got the following
error at this stage:

   On branch as/test-1
   Your branch and 'origin/as/test-1' have diverged,
   and have 1 and 2 different commits each, respectively.
     (use "git pull" to merge the remote branch into yours)
   You are currently cherry-picking commit 6e14805.

   nothing to commit, working tree clean
   The previous cherry-pick is now empty, possibly due to conflict resolution.
   If you wish to commit it anyway, use:

       git commit --allow-empty

   Otherwise, please use 'git reset'

-- 
()  ascii ribbon campaign -- against html e-mail
/\  http://preview.tinyurl.com/qcy6mjc [archived]

**Comment by ant-222** [comment]
Just in case, here is the error in context:
https://pastebin.com/raw/XipPnw3N

**Comment by dreamer** [comment]
Ah, sorry - I made a mistake, the correct commit to cherry-pick is 2b6d9f91527efdfa5b7146616d1b9578fcabd147 - the second commit from your review.

**Comment by ant-222** [comment]
Patryk:

> Ah, sorry - I made a mistake, the correct commit to
> cherry-pick is 2b6d9f91527efdfa5b7146616d1b9578fcabd147 -
> the second commit from your review.

I should have checked that but I don't know where you took
the short number instead of the 40-character hash.  I am
currently in this state:

    Ant@ant-519666801b8 ~/db-staging
    $ git log -n 3
    commit 7e4885bf6b67647a5c526f09eadaf20deb677c3d
    Merge: 2c5322d 2b6d9f9
    Author: Anton Shepelev <anton.txt@gmail.com>
    Date:   Sun Jan 19 23:23:29 2020 +0300

        Merge branch 'as/test-1' of github.com:dreamer/dosbox-staging into as/test-1

    commit 2c5322d135a79c4b944010e4d52f3160608f1073
    Author: ant-222 <43175957+ant-222@users.noreply.github.com>
    Date:   Sat Jan 18 22:33:44 2020 +0300

        Add a missing include of stdio.h for snprintf()

    commit 2b6d9f91527efdfa5b7146616d1b9578fcabd147
    Author: ant-222 <43175957+ant-222@users.noreply.github.com>
    Date:   Sun Jan 19 02:48:15 2020 +0300

        Provide aclocal with the path to additional .m4 files.


Shall I cherry-pick now, or do something else?  Maybe start
from a fresh clone (the newbie way!)...

**Comment by ant-222** [comment]
Patryk:

> After changing the name/email using `git config (...)
> commit authorship can be updated using
>     git commit --amend --reset-author

Shall I, in order to do that, go though cherry-picking each
commit?

**Comment by dreamer** [comment]
FYI: in Git you almost never need to use full 40-digits hash - "short hashes" are just unique prefixes of the full commit id. Just use first 4-8 digits of hash and you'll be fine in 99.99% of cases ;) (if those digits won't identify unique commit, Git will complain).

You don't need to do fresh clone either, as Git provides very helpful command: `git reset --hard <id>` which unconditionally resets your branch to a specified commit id. So whenever you want to go back to the version of commits you have already pushed, you can use:

    git reset --hard origin/as/test-1 # or some specific commit id

I suggest you reset and try again, as you seem to unintentionally created a merge commit between your local version of branch and remote version of branch. Nothing to worry about :)

**Alternatively**, you can create a completely new branch and then push from that new one to this review:

1. `git checkout master` (go back to master branch for a while)
2. `git pull` (download the latest changes)
3. `git checkout -b as/test-2` (create brand new branch)
4. `git cherry-pick 6e1480` (first commit of your two)
5. `git commit --amend --reset-author`
6. `git cherry-pick 2b6d9f` (second commit)
7. `git commit --amend --reset-author`
8. (tricky part) `git push --force -u origin as/test-2:as/test-1` (pushes your local branch as/test-2 to the remote branch as/test-1, which will update this review)

**Comment by dreamer** [comment]
FYI: in Git you almost never need to use full 40-digits hash - "short hashes" are just unique prefixes of the full commit id. Just use first 4-8 digits of hash and you'll be fine in 99.99% of cases ;) (if those digits won't identify unique commit, Git will complain).

You don't need to do fresh clone either, as Git provides very helpful command: `git reset --hard <id>` which unconditionally resets your branch to a specified commit id. So whenever you want to go back to the version of commits you have already pushed, you can use:

    git reset --hard origin/as/test-1 # or some specific commit id

I suggest you reset and try again, as you seem to unintentionally created a merge commit between your local version of branch and remote version of branch. Nothing to worry about :)

**Alternatively**, you can create a completely new branch and then push from that new one to this review:

1. `git checkout master` (go back to master branch for a while)
2. `git pull` (download the latest changes)
3. `git checkout -b as/test-2` (create brand new branch)
4. `git cherry-pick 6e1480` (first commit of your two)
5. `git commit --amend --reset-author`
6. `git cherry-pick 2b6d9f` (second commit)
7. `git commit --amend --reset-author`
8. (tricky part) `git push --force -u origin as/test-2:as/test-1` (pushes your local branch as/test-2 to the remote branch as/test-1, which will update this review)

**Comment by ant-222** [comment]
Patryk:

> After step 5, open review page and re-request review, so
> the reviewer is notified you don't plan further changes.

Here are the fixed commits:

    https://github.com/dreamer/dosbox-staging/pull/133/commits

Where is the Review page?

By the way, I have chaned my name and e-mail in ~/.gitconfig,
yet the log still shows my login and the `noreply' e-mail
even for new commits.  What else do I have to do?

**Comment by dreamer** [comment]
> Here are the fixed commits: https://github.com/dreamer/dosbox-staging/pull/133/commits Where is the Review page?

This is the review page :) Anyone can switch e.g. to tab "Files changed" and leave comments attached to specific lines. Your push automatically updated the review and triggered the CI (which already rebuilt your changes on 3 OSes in ~18 build configurations).

Thanks for your contribution, I'll merge it in a minute :)

**Comment by ant-222** [comment]
I wrote:

> Where is the Review page?

This is the PR page:
https://github.com/dreamer/dosbox-staging/pull/133
The only mention of "review" outside a message is the
"Reviewers" URL at the top of the right panel, but it does
not work with my current browser.  I will the MyPal browser.

**Comment by dreamer** [comment]
There should be 4 "tabs" under the PR name: Conversation, Commits, Checks, Files changed

Reviewers switch to the area they want to leave a comment in and the comments appear in that tab and also in "Convesation". Usually review comments are started in  "Files changed", attached to specific lines.

**Pull request merged**
