### PR TITLE
Add dosbox-staging icons

### PR DESCRIPTION
**Pull request by dreamer**
This is the first step towards #148. Icon files are not used for any build yet, but we can now use them for Windows and macOS builds; Linux uses *.png and *.svg files natively (but a .desktop icon correlating dosbox-staging to graphic file needs to be written).

The design is not final yet (especially for 16x16px icon, also 32x32px bitmap icon is missing), but I think it's already nice upgrade compared to the somewhat dated existing icon :)

Decided to store generated icons as LFS artefacts, as 300KB files are big enough (in my opinion) to negatively affect repo size if we'll go through several future design iterations.

[edit]
According to some comments I saw, using png files inside ico containers is supported on Windows starting with Vista… No idea how this will look like on XP.

### CODE REVIEW

**Comment by krcroft** [comment]
(Edit: I just re-read your PR comment about how the icons aren't used in any builds yet - so that answers my second question; please disregard)

**Comment by dreamer** [comment]
About LFS: I am still considering dumping .ico and .icns as simple files in the repo, especially when it'll be time to replace existing dosbox.ico… but I'm not sure; with files up to ~100KB I have no problems, but 300KB gives me pause… Each commit to these files would grow the repo by ~600KB (png files don't benefit from zlib compression of object files used by Git repo).

Anyways; LFS is actually really simple to use: install `git-lfs` (it is a separate program, distributed outside of Git), cd into repo and:

    git lfs install

LFS local hooks will be installed, and binary files marked to be managed by LFS will appear as proper files after next checkout (and they are transparently converted from binary files to LFS links and uploaded to LFS storage, it's really quite pleasant to use, especially when repo includes large binary files).

There are some problems with it as well: tool is written in Go, so I guess it won't run on Windows XP, GitHub is buggy when it comes to accepting external PRs with LFS links, and even `git lfs install` will make people trip over…

**Comment by krcroft** [comment]
When the icons/pngs/.. need to be updated, would it make sense to hard-remove all history of that specific file? We'd gain the benefit of these nicely living in our repo, while not suffering the size bloat over time.  And any old versions could be attached here or in the release archives, if anyone cares.

**Comment by dreamer** [comment]
With LFS? There's no need to - each revision of LFS artifact takes only few bytes in actual git repo (~130 bytes); so if we'll decide that "ok, this version of icon is here to stay for some time", we could replace LFS link with actual file and repo size won't be affected negatively :)

**Pull request merged**
