### PR TITLE
cga_mono patch

### PR DESCRIPTION
**Pull request by mzijlstra**
The CGA_MONO patch found at: https://www.vogons.org/viewtopic.php?p=587382#p587382

I also took into account Qbix's comment (https://www.vogons.org/viewtopic.php?p=592939#p592939) and created both SHELL_STARTUP_CGA and SHELL_STARTUP_CGA_MONO messages, putting the if statement where MSG_Get is used.

### CODE REVIEW

**Comment by dreamer** [comment]
OK, figured a way to manually trigger CI without changing our current workflow.

**Comment by mzijlstra** [comment]
Hi Dreamer,

Thanks for the detailed instructions and linked guidelines.  I have to admit that I'm not super experienced with this and thus really appreciate your help. 

I've updated my commit message as advised, but after I did so I was not able to push to my github.  The message it gave was: "Updates were rejected because the tip of your current branch is behind its remote counterpart", it also told me I could fix it with a pull... So I did, and then pushed to my github. 

I actually went through this process twice because I forgot to update the author and date the first time :|. 

Anyway, my main concern now is that the latest commit message on github is "Merge branch 'master' of github.com:mzijlstra/dosbox-staging". Which was generated by doing the pull. Is there a clean way to fix this, or is it not a problem? 

I used the date and author (VileRancour) of when the patch was initially posted. A different author (basic) added the paperwhite option later on. Best would probably be two separate commits, one for each author, but it seems like a lot of work for something not super important. Perhaps I should just mention in the commit message that the paperwhite option came from basic?

Thanks again for all your help!

Oh, would it also be good for me to update my fork to your latest version?

**Comment by dreamer** [comment]
> I've updated my commit message as advised, but after I did so I was not able to push to my github. The message it gave was: "Updates were rejected because the tip of your current branch is behind its remote counterpart", it also told me I could fix it with a pull... So I did, and then pushed to my github.
> 
> I actually went through this process twice because I forgot to update the author and date the first time :|.

Well, that's a rookie mistake, but no worries - everyone did it in the beginning when learning Git :)

The moment you amended your local commit, the history of your local branch (version on your computer) diverged from the remote branch (version stored on GitHub). Usually that happens when some other person pushed to the remote branch before you (thus pull creates a merge), but in this case you are the only person working on your fork, therefore the correct step was to `git push --force origin master` to overwrite whatever was stored on GitHub. Usually, you are not supposed to force push to master branch - but in this case it's the most appropriate way forward.

> Anyway, my main concern now is that the latest commit message on github is "Merge branch 'master' of github.com:mzijlstra/dosbox-staging". Which was generated by doing the pull. Is there a clean way to fix this, or is it not a problem?

Well, it's not a problem *really*, except it will be confusing for future readers of the code. Let's fix it (I could do it, but I think it's a safe exercise for you). See the end of this post for instructions.

> I used the date and author (VileRancour) of when the patch was initially posted. A different author (basic) added the paperwhite option later on. Best would probably be two separate commits, one for each author, but it seems like a lot of work for something not super important. Perhaps I should just mention in the commit message that the paperwhite option came from basic?

You actually literally attributed the authorship to "VogonsUser", but no worries - we'll fix it as well. Yeah, splitting this change into 2 commits would be nice, but in case of such small change keeping it in one commit will be good enough - we can attribute the change in commit message.

> Oh, would it also be good for me to update my fork to your latest version?

Instructions:
```
git reset --hard 95e6da9  # this will take you back in history exactly to the commit you amended
git commit --amend --author="VileRancour <VileRancour@vogons.org>"  # when amending message, remove lines starting with "Author" and "Date", add a sentence about additional paperwhite option
git remote add upstream git@github.com:dreamer/dosbox-staging.git # add my repo as remote named "upstream"
git fetch --all  # download latest changes from all remotes
git rebase upstream/master  # rebase commit on top of the latest version of master branch in my repo
git push --force origin master # overwrite master branch of your fork
```
In the result Pull Request will be updated with clean history and your fork will be updated to include all the latest changes from master branch of my repo :).

**Comment by mzijlstra** [comment]
Thank you again for your excellent guidance. 

I believe everything is set now :)

**Comment by dreamer** [comment]
I just merged-in this change as ffe3c5a.

Normally, I would close the review now, but let's test how GitHub will behave if I'll try to rebase&merge option via GitHub interface (hopefully it will close the PR without generating empty commit).

**Comment by dreamer** [comment]
Yup, GitHub behaved sanely, good to know.

@mzijlstra Thank you! This is a very nice addition :)

**Pull request merged**
