### PR TITLE
Enable parallel builds in VS for all configs

### PR DESCRIPTION
**Pull request by pmcmorris**
Minor change for faster builds on Windows

### CODE REVIEW

**Comment by pmcmorris** [comment]
I did a --amend and pushed.  Did that work?

**Comment by dreamer** [comment]
@pmcmorris You made a tiny mistake in doing `git pull`, `git push` instead of `git push --force origin multicore_build` - that's why unnecessary merge commit got tangled up in PR. Correction will be easy :)

Use following sequence of commands, please:
```
git checkout multicore_build # to make sure you're using the correct branch
git reset --hard b81eb59 # this will take you back to state before pull and merge commit
git push --force origin multicore_build # this will overwrite your remote branch and automatically update the review
```

**Comment by dreamer** [comment]
@pmcmorris I don't have access to my private messages on Vogons any more, where you left me tips on what needs to be fixed in VS builds, so thanks for taking pro-active stance and submitting this change :)

I cherry-picked your commit to master branch manually; it's now included in master, but because I did it manually, and GitHub is bad at detecting when PR can be closed as fixed, I need to close it manually as well.

Merged-in as 82a3a46550f4f937943dd35738752fadddc2d6fa. Thank you!

**Comment by pmcmorris** [comment]
Sorry for the delay, I don't get to work on this stuff as often as I would like.

Here is the message from Vogons but I think most has been addressed already:
```
Yes, the dosbox-staging project has a much nicer build process.

I built it with Visual Studio 2017 as that's what I have installed (I'll upgrade later)

The only minor issues I encountered were:

1) To build with heavy debugging enabled, you also need PS:\> .\vcpkg install pdcurses
2) The VS solutions don't have multiprocessor compilations enabled by default (so the build used one core and is long) (e.g. <MultiProcessorCompilation>true</MultiProcessorCompilation>)
3) The folder structure in the VS solution doesn't reflect the file layout and is hard to read. I'm assuming the solution file is generated rather that created by hand. Maybe it's easy to fix?
4) I needed to adjust the Windows SDK version and Platform Toolset to what I have installed. This is totally normal and but can be unexpected for beginners. It would be nice to add a note in the build instructions that they may need to adjust them (or install matching SDK and toolset).
5) I get an assert in SDL_SetWindowIcon() in SDL_video.c:1774 but it's non-fatal and can be ignored

Also, the set sdl_videodriver=windib workaround wasn't necessary for SDL2 (it's and SDL1.2 only issue). You may also wish to add a preprocessor define for _CRT_SECURE_NO_WARNINGS unless you plan on migrating to the MS "secure" functions (unlikely for cross-platform code).

Thanks for the updated DosBox!

Patrick
```

**Comment by kcgen** [comment]
> 1) To build with heavy debugging enabled, you also need PS:\> .\vcpkg install pdcurses

@pmcmorris , I'm not sure if you used our `./scripts/list-build-dependencies.sh` script, but it prints a list of packages specific to your package manager. 

```
 ./scripts/list-build-dependencies.sh 
Please specify the --manager argument with one of: apt brew dnf macports msys2 pacman vcpkg zypper
```

So we give it `--manager vcpkg` or `-m vcpkg` for short:

```
./scripts/list-build-dependencies.sh -m vcpkg
Please specify the --compiler argument with one of: gcc clang
```

And finally a `--compiler` (or `-c` for short)

```
./scripts/list-build-dependencies.sh -m vcpkg -c gcc
```

And it gives back: `zstd libpng pdcurses sdl2 sdl2-net opusfile`

**Pull request closed without merging**
