### PR TITLE
Build release with AutoFDO data and link-time-optimizations

### PR DESCRIPTION
**Pull request by krcroft**
This PR adds AutoFDO data and link-time-optimizations to the Linux release build. 

The AutoFDO data is generated from sample-based measurements collected from 144 tests (listed below) that exercise performance-related aspects of DOSBox: all CPU cores; all machine types; various memory sizes; real and protected modes; all scalers and GLShaders; all SDL modes; all Sound Blaster types; speaker types: beeper, tandy, and disney/CMS; Gravis UltraSound rates and MIDI; and CD-DA playback track types: codecs, frequencies, stereo & mono.

The combination of compiler optimization flags was selected from an exhaustive set of benchmarks testing all permutations of O-levels (Os, O2, O3, and Ofast), architecture tuning (with and without), FDO (with and without), and Link-time-optimizations. 

As usual with FDO, thorough measurements proved more informative for the optimizer (ie: produced the fastest binaries) than simply using generalized architecture and performance-level rules (O3/Ofast). The fastest combination was -O2 using feedback data (FDO) and when allowed to optimize the entire code space as a whole (LTO).

The resulting binary produces Quake bench scores roughly 10% faster than a standard O3 build (when cycles are set to a dynamic value, like `max` or `max 97%`).  Not a huge boost, but roughly on par with other sample-based AutoFDO results. This binary is faster than anything I can compile locally (also using gcc 9.x).

List of sample-profiled tests (the results of which were merged into one big AFDO record used the optimize the release):

**cores: running 3 tests**
```
  - profiling dynamic  [passed]
  - profiling normal   [passed]
  - profiling simple   [passed]
```

**machines: running 13 tests**
```
  - profiling cga      [passed]
  - profiling cga_mono [passed]
  - profiling ega      [passed]
  - profiling hercules [passed]
  - profiling pcjr     [passed]
  - profiling svgaet3k [passed]
  - profiling svgaet4k [passed]
  - profiling svgapara [passed]
  - profiling svga_s3  [passed]
  - profiling vgaonly  [passed]
  - profiling tandy    [passed]
  - profiling vesanolf [passed]
  - profiling vesaoldv [passed]
```

**memsize: running 8 tests**
```
  - profiling ldfix-32 [passed]
  - profiling loadfix  [passed]
  - profiling ldfix-96 [passed]
  - profiling mem-1    [passed]
  - profiling mem-3    [passed]
  - profiling mem-16   [passed]
  - profiling mem-8    [passed]
  - profiling mem-63   [passed]
```

**scalers: running 31 tests**
```
  - profiling asp-on   [passed]
  - profiling asp-off  [passed]
  - profiling gl-adm3x [passed]
  - profiling gl-adm2x [passed]
  - profiling gl-adv2x [passed]
  - profiling gl-adv3x [passed]
  - profiling gl-rgb2x [passed]
  - profiling gl-rgb3x [passed]
  - profiling gl-scn2x [passed]
  - profiling gl-scn3x [passed]
  - profiling gl-sharp [passed]
  - profiling gl-tv2x  [passed]
  - profiling gl-tv3x  [passed]
  - profiling noscale  [passed]
  - profiling sc-adm2x [passed]
  - profiling sc-adm3x [passed]
  - profiling sc-adv2x [passed]
  - profiling sc-adv3x [passed]
  - profiling sc-hq2x  [passed]
  - profiling sc-hq3x  [passed]
  - profiling sc-nrm2x [passed]
  - profiling sc-nrm3x [passed]
  - profiling sc-rgb2x [passed]
  - profiling sc-rgb3x [passed]
  - profiling sc-s2sai [passed]
  - profiling sc-scn2x [passed]
  - profiling sc-scn3x [passed]
  - profiling sc-sup2x [passed]
  - profiling sc-supea [passed]
  - profiling sc-tv2x  [passed]
  - profiling sc-tv3x  [passed]
```

**sdl-modes: running 16 tests**
```
  - profiling f-no-o-o [passed]
  - profiling f-no-s-s [passed]
  - profiling f-no-t-o [passed]
  - profiling f-no-t-s [passed]
  - profiling f-vs-o-o [passed]
  - profiling f-vs-s-s [passed]
  - profiling f-vs-t-o [passed]
  - profiling f-vs-t-s [passed]
  - profiling w-no-o-o [passed]
  - profiling w-no-s-s [passed]
  - profiling w-no-t-o [passed]
  - profiling w-no-t-s [passed]
  - profiling w-vs-o-o [passed]
  - profiling w-vs-t-o [passed]
  - profiling w-vs-s-s [passed]
  - profiling w-vs-t-s [passed]
```

**sound-blaster: running 6 tests**
```
  - profiling gb       [passed]
  - profiling sb1      [passed]
  - profiling sb16     [passed]
  - profiling sb2      [passed]
  - profiling sbpro1   [passed]
  - profiling sbpro2   [passed]
```

**speaker: running 3 tests**
```
  - profiling disney   [passed]
  - profiling speaker  [passed]
  - profiling tandy    [passed]
```

**stress-nolfb: running 8 tests**
```
  - profiling doom-max [passed]
  - profiling doom-min [passed]
  - profiling q-norm0  [passed]
  - profiling q-norm10 [passed]
  - profiling q-norm12 [passed]
  - profiling quakem0  [passed]
  - profiling quakem10 [passed]
  - profiling quakem12 [passed]
```

**stress-s3: running 8 tests**
```
  - profiling doom-max [passed]
  - profiling doom-min [passed]
  - profiling q-norm0  [passed]
  - profiling q-norm10 [passed]
  - profiling quakem0  [passed]
  - profiling quakem10 [passed]
  - profiling q-norm12 [passed]
  - profiling quakem12 [passed]
```

**stress-vgaonly: running 8 tests**
```
  - profiling doom-max [passed]
  - profiling doom-min [passed]
  - profiling q-norm0  [passed]
  - profiling q-norm10 [passed]
  - profiling q-norm12 [passed]
  - profiling quakem0  [passed]
  - profiling quakem10 [passed]
  - profiling quakem12 [passed]
```

**ultrasound: running 4 tests**
```
  - profiling gus11    [passed]
  - profiling gus22    [passed]
  - profiling gus44    [passed]
  - profiling gus-midi [passed]
```

**cd-da: running 60 tests**
```
  - profiling fm-16-22 [passed]
  - profiling fm-16-44 [passed]
  - profiling fm-16-48 [passed]
  - profiling fm-16-88 [passed]
  - profiling fm-24-96 [passed]
  - profiling fm-8-11  [passed]
  - profiling fs-16-22 [passed]
  - profiling fs-16-44 [passed]
  - profiling fs-16-48 [passed]
  - profiling fs-16-88 [passed]
  - profiling fs-24-96 [passed]
  - profiling fs-8-11  [passed]
  - profiling mm-16-22 [passed]
  - profiling mm-16-44 [passed]
  - profiling mm-16-48 [passed]
  - profiling mm-16-88 [passed]
  - profiling mm-24-96 [passed]
  - profiling mm-8-11  [passed]
  - profiling ms-16-22 [passed]
  - profiling ms-16-44 [passed]
  - profiling ms-16-48 [passed]
  - profiling ms-16-88 [passed]
  - profiling ms-24-96 [passed]
  - profiling ms-8-11  [passed]
  - profiling om-16-22 [passed]
  - profiling om-16-44 [passed]
  - profiling om-16-48 [passed]
  - profiling om-16-88 [passed]
  - profiling om-24-96 [passed]
  - profiling om-8-11  [passed]
  - profiling os-16-22 [passed]
  - profiling os-16-44 [passed]
  - profiling os-16-88 [passed]
  - profiling os-16-48 [passed]
  - profiling os-24-96 [passed]
  - profiling os-8-11  [passed]
  - profiling vm-16-22 [passed]
  - profiling vm-16-44 [passed]
  - profiling vm-16-48 [passed]
  - profiling vm-16-88 [passed]
  - profiling vm-24-96 [passed]
  - profiling vm-8-11  [passed]
  - profiling vs-16-22 [passed]
  - profiling vs-16-44 [passed]
  - profiling vs-16-48 [passed]
  - profiling vs-16-88 [passed]
  - profiling vs-24-96 [passed]
  - profiling vs-8-11  [passed]
  - profiling wm-16-22 [passed]
  - profiling wm-16-44 [passed]
  - profiling wm-16-48 [passed]
  - profiling wm-16-88 [passed]
  - profiling wm-24-96 [passed]
  - profiling wm-8-11  [passed]
  - profiling ws-16-22 [passed]
  - profiling ws-16-44 [passed]
  - profiling ws-16-48 [passed]
  - profiling ws-16-88 [passed]
  - profiling ws-24-96 [passed]
  - profiling ws-8-11  [passed]
```

### CODE REVIEW

**Comment by grapeli** [comment]
> The resulting binary produces Quake bench scores roughly 10% faster than a standard O3 build (when cycles are set to a dynamic value, like `max` or `max 97%`). Not a huge boost, but roughly on par with other sample-based AutoFDO results. This binary is faster than anything I could compile locally (also using gcc 9.x).
10% is not enough, it is a lot.
Hats off. A fantastic job. Respect.

I really like this kind of work.

**Comment by krcroft** [comment]
Thanks @grapeli ; yeah - it's pretty hard to beat sample-based feedback! 

I prefer it (AutoFDO) over profile-based feedback (PGO), because the sampling data is portable to different architectures, operating systems, and to both GCC and Clang (despite the fact that it needs to be collected using a custom Linux kernel running on an Intel processor that supports the Last Branch Record (LBR) measurement feature).  

And unlike PGO-collected data that can only be used when building the exact same source tree (and become useless the moment we make another commit; causing the compiler to spew errors),  performance samples on the other hand are still useful even when the code keeps evolving; however they graceful degrade as more and more performance-related code changes.  That said, I don't plan to let our performance samples degrade, and will refresh them every week or so against master.

I also plan to write up notes on how other Linux users running LBR-capable processors can setup their own sampling, and ensure we have a group of people who can provide this (incase I'm hit by a bus or killed by corona-virus!)

We could also have used the same sample feedback for our macOS release, but alas hit one snag:
 https://github.com/dreamer/dosbox-staging/issues/210, but hopefully Google addresses it next release.

**Comment by dreamer** [comment]
For users, who want to try it out, direct download link to CI build: [dosbox-staging-linux-v0.75.0-pre-636-g2fe8](https://github.com/dreamer/dosbox-staging/suites/515946623/artifacts/2818287)

I did some quick play-testing in 2 titles
- Quake (Steam; game version 1.08), 640x480, using Steam overlay for FPS counter - during play the counter stays at dosbox-locked 70FPS, the game is super smooth. Timedemo 1 in this resolution goes somewhat below 60FPS, but for software-only renderer running in an emulator - this is great and noticeably better than my usual tests.
- Descent II (Steam; game version 1.2), 640x480+cockpit - using both FRAMETIME "cheatcode" to display FPS and Steam overlay FPS counter. When playing through first level FPS is smooth 70FPS (Steam overlay) ~80-~220 FPS (in-game counter). This game has the most demanding 3D software-rendered built-in demo I know (DESCENT2.DEM) - this build dips below 30 FPS only several times (significantly better than other DOSBox builds I tested)

I compared Descent II to DOSBox 0.74-3 (Fedora rpm) and latest dosbox-staging master (release build -O3 with -march=haswell - my native arch). My (unscientific) results of AutoFDO build were:
- compared to 0.74-3: looks like ~+80% better results (it's comparing apples to oranges, because 0.74-3 is missing most of SVN trunk improvements, I know)
- compared to local -O3 build: +~5% better results

(all tests using `output=opengl`, `cycles=max 95%`, in fullscreen `fullresolution=1920x1080`)

Probably tomorrow I will dig into the review a bit more :)

**Comment by grapeli** [comment]
@dreamer 
The most authoritative comparison will be in relation to master snapshot build.
@krcroft 
AutoFDO has one more important advantage - the time-consuming stage of compilation of an instrumented version of the program is missing (this is not important for this project, but for example chromium).
Have you also tried to profile SDL2? How much influence this library has on the overall dosbox-staging performance.

**Comment by krcroft** [comment]
> Have you also tried to profile SDL2? How much influence this library has on the overall dosbox-staging performance.

No - but that's interesting!

If we included dependent sources as git submodules (assuming they're also Git-based projects), we could built and link them as static libraries - then we could do what your suggesting. Users would not only benefit performance-wise, but also functionality-wise as they would be using the latest SDL sources instead of whatever older libraries is shipped via their package-manager.

**Comment by krcroft** [comment]
@dreamer ,  I've added three `stress-*` groups to the tests covering `vgaonly`, `svga_s3`, and `vesa_nolfb` machine types. Right now Doom and Quake timedemos make up the jobs in those cases (at various resolutions).  It would be fantastic if we could added Descent II to them for the reasons you've mentioned.

Is it possible to start the `DESCENT2.DEM` demo automatically (instead of it sitting at the main menu?).  Google searches have come up dry for me.  Alternatively - any other games that launch straight into intensive demos or playback are also options.

**Comment by krcroft** [comment]
New binary incorporates the Quake and Doom stress tests profiles, plus the commit that make the FDO-training build slightly more representative to the release build by defining `-DNDEBUG`. 

https://github.com/dreamer/dosbox-staging/suites/518113500/artifacts/2858923  

For my benchmarks, I lock my processor at a fixed speed (either writing 1 or 100 to both `/sys/devices/system/cpu/intel_pstate/min_perf_pct` and `min_perf_pct`) and do 5 runs, then take the best number.  This new binary's clocked in 0.7% above the prior profile build. Lol. Not much left! That said, the more functionality we can exercise the more we optimize all the areas that DOSBox emulates.

**Comment by krcroft** [comment]
I will write up notes describing how to setup a sampling environment to generate feedback data for DOSBox optimization.  I think that will open up this aspect of it, and make it less like a voodoo black box :-)
The great thing with this data is that its not OS-specific, so it fully applies to x86_64  macOS and Windows builds (if we want to use clang or gcc-compiled binaries). 

It will also let us build feedback optimized SDL2 sources (and ship either static or shared objects for macOS and Windows); where we might see even bigger gains. That's for another PR though. This just puts the overall approach in-place. 

I will rebase to get this back in sync with the latest CI updates.

**Comment by dreamer** [comment]
This review is waiting for quite some time, so I'll describe why I haven't finished the review yet:

- I am worried about adding more dependencies / complicating our snapshot builds - they are quite complicated already; I seems like `autofdo` package is available via Ubuntu repositories already - is it outdated or otherwise missing something? I am ok with using it for our actual release/test-release builds, but for snapshots - I'm not sure yet.
- I am a bit worried about reproducibility - I had problems running the tests in our dosbox-tests repo (this might be something specific to my setup though)
- GNU parallel behaves a bit weirdly, and it might affect new users - in the beginning, it was spamming me with messages reminding me about citation if it is being used for scientific work… it's ok, but we probably should make sure, that this won't affect users, who run our scripts on the clean installation.

**Comment by krcroft** [comment]
All good points @dreamer.

 I will try to use the package manager's AutoFDO; this means we will step back to building with the default gcc (which I think is 7.x on Ubuntu 16.04); so that will further simplify this PR. 

 I should also be able to swap xargs and avoid parallel. 

Let me know what happened when running the test suite; I haven't tested it on other platforms (or distros), so surely has some  some issues to work out.

**Comment by krcroft** [comment]
Moving this PR to a new branch; will resume discussion there.

**Pull request closed without merging**
