### PR TITLE
Expand mouse control methods

### PR DESCRIPTION
**Pull request by krcroft**
Replaces the `autolock = true/false` configuration setting with `mouse_control = ...` having a two-value setting.

The first value defines how the mouse is controlled:

- **onclick**:   The mouse will be captured after the first click inside the window.
- **onstart**:   The mouse is captured immediately on start (similar to real DOS).
- **seamless**:           The mouse can move seamlessly in and out of DOSBox _and cannot be captured_.
- **nomouse**:            The mouse is disabled and hidden without any input sent to the game.

The second value defines how middle-clicks are handled:

- **middlegame**:    Middle-clicks are sent to the game (not used to uncapture the mouse).
- **middlerelease**:  Middle-click will uncapture the mouse when windowed (not sent to the game).  However, middle-clicks are always sent to the game when `fullscreen` or when `seamless` control is set.

The default setting of `onclick middlegame` reproduces DOSBox's existing behavior.

State is retained across full-screen and windowed transitions. The minimum number of capture/visibility toggles are made (typically one or none) during the various window events resulting a consistent and solid feel to mouse behavior.

### CODE REVIEW

**Comment by krcroft** [comment]
Tested all permutations of fullscreen (true/false), with capture_mouse (onstart/onclick/seamless/never) and (middlegame/middlerelease) on Linux X11 (hardware), MacOS (VM), Windows 7 VM, and Windows 10 (hardware).

@dreamer_, I'm hoping that this operates (at least a bit better) on Wayland.

**Comment by dreamer** [comment]
I'll follow up with testing on XWayland and native Wayland - probably tomorrow.

**Comment by krcroft** [comment]
Thank you @dreamer ,

If we can make a borderless window-mode (that happens to render at full-desktop resolution), then in theory it would not be considered fullscreen, and 'seamless' mode would work.

We could move from the current:

``` ini
[sdl]
fullscreen = true/false
windowmode = true/false
```

To a single setting:

``` ini
[sdl]
screen = full / borderless / window
```

Where borderless consumes the full desktop resolution and sets the windowsless flag in SDL.  So might not be too invasive either.

Thanks for the kicking the tires on Wayland. If it does have issues I will follow up with SDL to see if there's some special needed (right now everything has fortunately behaved OS-agnostically and mostly as described.. although order of operations proved very important to get `onstart` working right across all the OSes; had to be done after the display reaches the EXPOSED state).

**Comment by arrowgent** [comment]
two part issue related to middle mouse:

1)
the .conf default is fine, it should have more information in output
when `capture_mouse    = onclick`
```
"" is not a valid value for variable: middle_control.
It might now be reset to the default value: middlerelease
```
because the second parameter is not defined
if it told you which variable was undefined it would be simpler to locate (less than a minute)

2)
middle mouse should not still capture/uncapture the mouse with this setting
```
capture_mouse    = onclick middlegame
```
as noted by the conf details:
`#                      middlegame:     Middle-clicks are sent to the game`
`#                                      (Ctrl-F10 uncaptures the mouse).`
only left click or right click should capture the mouse

i was trying to find a setting that ignored middle mouse but there does not seem to be any setting for this

**Comment by kcgen** [comment]
Interesting @arrowgent - regarding 2. perhaps a third options, `middleignore` would suffice?

**Comment by arrowgent** [comment]
> @arrowgent - regarding 2. perhaps a third options, `middleignore` would suffice?

considering its dos, there are few reasons the middle button would be used
but there are those games out there middle button is used

if it just ignored the capture/uncapture but passed the button to the game.
which is what i thought `middlegame` was supposed to do?

**Comment by kcgen** [comment]
Arrowgent, tentative fixes are here: https://github.com/dosbox-staging/dosbox-staging/pull/563

If you have a build environmen, can you try:  `kc/fix-middle-game-1`

If not, then binaries will be produces shortly here:

https://github.com/dosbox-staging/dosbox-staging/pull/563

**Pull request merged**
